In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl

In [103]:
cars = pd.read_csv("./cars.csv")
cars.sample(10)

         brand  km_driven    fuel                 owner  selling_price
7905    Maruti     141000  Diesel  Fourth & Above Owner         700000
1174  Mahindra      70000  Diesel          Second Owner         254999
5547      Audi     110000  Diesel           First Owner        1200000
3238    Jaguar      45000  Diesel           First Owner        3200000
4019      Audi     110000  Diesel          Second Owner        1750000
3142      Tata      85700  Diesel          Second Owner         175000
5029    Maruti     100000  Petrol  Fourth & Above Owner         150000
2962     Skoda      70000  Diesel           Third Owner         220000
1380      Ford      63982  Diesel           First Owner         850000
4821    Maruti      58343  Petrol           First Owner         225000

In [104]:
cars["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [105]:
cars["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [106]:
cars["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [107]:
print(f"Total number of unique Brands {cars["brand"].nunique()}\nTotal number of unique Owners {cars["owner"].nunique()}\nTotal number of unique Fuels {cars["fuel"].nunique()}")

Total number of unique Brands 32
Total number of unique Owners 5
Total number of unique Fuels 4

# ONE HOT ENCODING

### Using Pandas

Without droping (n)

In [108]:
p_ohe = pd.get_dummies(data= cars, columns= ["fuel", "owner"])
p_ohe

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

K-1 OHE (With droping (n-1))

In [109]:
k1_ohe = pd.get_dummies(data= cars, columns= ["fuel", "owner"], drop_first= True)
k1_ohe

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### Using Scikit-Learn

In [110]:
x_train, x_test, y_train, y_test = skl.model_selection.train_test_split(cars.iloc[::, :4:], cars.iloc[::, -1], test_size= 0.2, random_state= 0)
oneHotEncoding = skl.preprocessing.OneHotEncoder(drop= "first", sparse_output= True, dtype= np.int32)

In [111]:
# One Hot Encoder always produce Sparse Matrix
x_train_ohe = oneHotEncoding.fit_transform(x_train[["fuel", "owner"]]).toarray()
x_test_ohe = oneHotEncoding.transform(x_test[["fuel", "owner"]]).toarray()

In [112]:
aa = np.hstack((x_train[["brand", "km_driven"]].values, x_train_ohe)) # Remember use the tuple here in hstack function ()

In [ ]:
pd.DataFrame(aa)

               0       1  2  3  4  5  6  7  8
0        Hyundai   60000  0  1  0  0  0  0  0
1           Tata  150000  1  0  0  0  0  0  1
2        Hyundai  110000  1  0  0  0  1  0  0
3       Mahindra   28000  1  0  0  0  1  0  0
4         Maruti   15000  0  0  1  0  0  0  0
...          ...     ... .. .. .. .. .. .. ..
6497        Tata   70000  1  0  0  0  0  0  1
6498        Ford  100000  1  0  0  0  1  0  0
6499     Hyundai   90000  0  0  1  0  1  0  0
6500  Volkswagen   90000  1  0  0  0  0  0  0
6501     Hyundai  110000  0  0  1  0  0  0  0

[6502 rows x 9 columns]

## ONE HOT ENCODING FOR BRAND (Which has many catagories)

In [114]:
count = cars["brand"].value_counts()
count

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [115]:
cars["brand"].nunique()
threashold = 100

In [116]:
repl = count[count <= threashold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='str', name='brand')

In [117]:
mv_ohe = pd.get_dummies(cars["brand"].replace(repl, "uncommon"))
mv_ohe

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False